# this configuration is intended for use at https://code.ornl.gov

variables:
  SCHEDULER_PARAMETERS: "-P CHM137 -W 1:30 -nnodes 1 -alloc_flags gpumps"
  EXTERNAL_WORKDIR: /gpfs/wolf/chm137/proj-shared/ci/${CI_PIPELINE_ID}

  # for script test
  DATA_DIR: /gpfs/wolf/chm137/proj-shared/spinifel_data
  DATA_FILENAME: 2CEX-10k-2.h5
  OUT_DIR: /gpfs/wolf/chm137/proj-shared/ci/${CI_PIPELINE_ID}/spinifel_output

  # for pytest
  test_data_dir: /gpfs/wolf/chm137/proj-shared/spinifel_data/testdata

  THREADS: 4 # reduce parallelism to avoid OOM in Legion build

stages:
  - build
  - unit_test
  - test
  - cleanup

build:
  stage: build
  before_script:
    - mkdir -p $(dirname ${EXTERNAL_WORKDIR})
    - cp -r ${CI_PROJECT_DIR} ${EXTERNAL_WORKDIR}
    - cd ${EXTERNAL_WORKDIR}
    - git clean -fxd
    - git submodule update --init --recursive
  script:
    - ./setup/build_from_scratch.sh
  tags:
    - nobatch

unit_test:
  stage: unit_test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
  script:
    - ./scripts/test.sh
  tags:
    - batch

test_mpi:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
    - mkdir -p ${OUT_DIR}
    - source ./setup/env.sh
  script:
    - jsrun -n1 -a1 -g1 python -m spinifel --default-settings=summit_ci.toml --mode=mpi
  tags:
    - batch

test_legion:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
    - mkdir -p ${OUT_DIR}
    - source ./setup/env.sh
    - export PYTHONPATH=${PYTHONPATH}:${EXTERNAL_WORKDIR}
  script:
      - jsrun -n1 -a1 -g1 legion_python -ll:py 1 -ll:csize 8192 legion_main.py --default-settings=summit_ci.toml --mode=legion runtime.use_cufinufft=false
  tags:
    - batch

test_sequential:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
    - mkdir -p ${OUT_DIR}
    - source ./setup/env.sh
  script:
    - jsrun -n1 -a1 -g1 python -m spinifel --default-settings=summit_ci.toml --mode=sequential
  tags:
    - batch

test_large:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
    - mkdir -p ${OUT_DIR}
    - source ./setup/env.sh
  script:
    - jsrun -n1 -a1 -g1 python -m spinifel --default-settings=summit_ci.toml --mode=mpi runtime.small_problem=false
  tags:
    - batch

test_finufft:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
    - mkdir -p ${OUT_DIR}
    - source ./setup/env.sh
  script:
    - jsrun -n1 -a1 -g1 python -m spinifel --default-settings=summit_ci.toml --mode=mpi runtime.use_cufinufft=false
  tags:
    - batch

test_nocuda:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
    - mkdir -p ${OUT_DIR}
    - source ./setup/env.sh
  script:
    - jsrun -n1 -a1 -g1 python -m spinifel --default-settings=summit_ci.toml --mode=mpi runtime.use_cufinufft=false runtime.use_cuda=false

  tags:
    - batch

old_test_mpi:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
  script:
    - bash ./scripts/run_summit_mult.sh -m -n 1 -a 1 -g 1 -r 1 -d 1 -c -f -s -e
  tags:
    - batch

old_test_legion:
  stage: test
  before_script:
    - cd ${EXTERNAL_WORKDIR}
  script:
    - bash ./scripts/run_summit_mult.sh -L -n 1 -a 1 -g 1 -r 1 -d 1 -c    -s -e # -f
  tags:
    - batch

cleanup:
  stage: cleanup
  before_script:
  script:
    - rm -rf ${EXTERNAL_WORKDIR}
  tags:
    - nobatch
