# This toml file contains settings for the Cori quicktart

[debug]
test = "Quickstart settings for Cori"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "${CFS}/m2859/data/3iyf/clean"
out_dir = "${SCRATCH}/spinifel_output/qfilling_forward_div2"
name = "3iyf_dp005_128x128pixels_500k.h5"

[detector]
shape = [1, 128, 128]

[psana]
enable = false
ps_smd_n_events = 10000
ps_eb_nodes = 1
ps_srv_nodes = 0

[runtime]
N_images_per_rank = 2500
use_cuda = false
use_cufinufft = false
use_cupy = false
use_single_prec = false
chk_convergence = false

[gpu]
devices_per_node = 1

[algorithm]
N_generations = 2
nER = 50
nHIO = 50
beta = 0.5
cutoff = 0.05
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 10000  # model_slices
N_batch_size = 100
