# This toml file contains settings for the Cori quicktart

[debug]
test = "Quickstart settings for Cori"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
out_dir = "${SCRATCH}/spinifel_output/"

[detector]
shape = [1, 128, 128]

[psana]
enable = true 
ps_smd_n_events = 10000
ps_eb_nodes = 1
ps_srv_nodes = 0
ps_dir = "${CFS}/m2859/data/3iyf/xtc2"      
exp = "xpptut15"
runnum = 1

[runtime]
N_images_per_rank = 2000
use_cuda = true
use_cufinufft = true
use_cupy = true
use_single_prec = true
chk_convergence = true

[gpu]
devices_per_node = 1

[algorithm]
N_generations = 20
nER = 50
nHIO = 25
beta = 0.3
cutoff = 0.05
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 10000  # model_slices
N_batch_size = 100
N_images_max = 10000

[fsc]
ref_path="setup/skopi/examples/input/pdb/3iyf.pdb"
fsc_zoom=0.6
fsc_nsearch=420

