# This toml file contains settings for the summit quickstart

[debug]
test = "Quickstart settings for Frontier"
verbose = true
verbosity = 5
use_callmonitor = false
checkpoint = false

[data]
in_dir = "${test_data_dir}/3IYF"
out_dir = "${out_dir}"
name = "3iyf_sim_10k.h5"

[detector]
shape = [1, 128, 128]

[psana]
enable = false
ps_smd_n_events = 10000
ps_eb_nodes = 1
ps_srv_nodes = 0

[runtime]
N_images_per_rank = 1000
use_cuda = true
use_cufinufft = true
use_cupy = true
use_fftx = true
use_single_prec = false
use_pygpu = true
chk_convergence = false

[gpu]
devices_per_node = 1

[algorithm]
N_generations = 4 # WAS 30
nER = 50
nHIO = 25
beta = 0.3
cutoff = 0.05
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 10000  # model_slices
N_batch_size = 1000
N_images_max = 6000

