# This toml file contains settings for multiple conformations hdf5 file/Frontier/Crusher
[debug]
test = "CI settings for multiple conformations on Frontier/Crusher"
verbosity = 0
use_callmonitor = false
[data]
in_dir = "${test_data_dir}"
out_dir = "${out_dir}"
name = "3iyf_3j03_128x128_1M.h5"
[detector]
shape = [1, 128, 128]
[psana]
enable = false
ps_smd_n_events = 1000
ps_eb_nodes = 1
ps_srv_nodes = 0
ps_batch_size=1000
ps_dir = "${test_data_dir}"
exp = "xpptut15"
runnum = 1
ps_parallel = "legion"
detname = "amopnccd"
[runtime]
N_images_per_rank = 1000
use_cuda = true
use_cufinufft = true
use_cupy = true
use_single_prec = false
chk_convergence = true
must_converge = false
[gpu]
devices_per_node = 1
[algorithm]
nER = 50
nHIO = 25
beta = 0.3
cutoff = 0.05
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 10000 # model_slices
N_batch_size = 1000         
[fsc]
pdb_path = "${test_data_dir}/mult_conf_data"
fsc_zoom = 0.6
fsc_nsearch = 420
