# This toml file contains settings for the Perlmutter quicktart

[debug]
test = "Quickstart settings for Cori"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "${in_dir}"
out_dir = "${out_dir}"
name = "${in_fname}"

[detector]
shape = [1, 128, 128]

[psana]
enable = false
ps_smd_n_events = 0

[runtime]
N_images_per_rank = 1000
use_cuda = true
use_cufinufft = true
use_cupy = true
use_single_prec = false

[gpu]
devices_per_node = 1

[algorithm]
N_generations = 25
nER = 51
nHIO = 25
beta = 0.9
cutoff = 5e-2
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 10000  # model_slices
N_batch_size = 2000
N_images_max = 10000

[fsc]
pdb_path="/pscratch/sd/z/zhantao/dgp3d_spi/pdb/pdb_repo/${pdb}.pdb"
fsc_fraction_known_orientations = 0.0
fsc_zoom=0.3
fsc_nsearch=420
fsc_min_cc=0.99         # see https://gitlab.osti.gov/mtip/spinifel/-/wikis/Perlmutter-Baseline-Convergence
fsc_min_change_cc=0.01