# This toml file contains settings for the converge/Summit
[debug]
test = "Quickstart settings for Converge on Summit"
verbose = true
verbosity = 0
use_callmonitor = false
[data]
in_dir = "${CFS}/m2859/data/3iyf/clean"
out_dir = "${SCRATCH}/spinifel_output"
name = "3iyf_128x128pixels_500k.h5"
[detector]
shape = [1, 128, 128]
[psana]
enable = false
ps_smd_n_events = 2500
ps_eb_nodes = 1
ps_srv_nodes = 0
ps_batch_size=2500
ps_dir = "/global/cfs/cdirs/m2859/data/3iyf/demo/xtc2"
exp = "xpptut15"
runnum = 1
ps_parallel = "legion"
[runtime]
N_images_per_rank = 2500
use_cuda = true
use_cufinufft = true
use_cupy = true
use_single_prec = true
chk_convergence = true
must_converge = true
[gpu]
devices_per_node = 1
[algorithm]
#N_generations = 30
N_generations = 4
#N_images_max = 10000
nER = 50
nHIO = 25
beta = 0.3
cutoff = 0.05
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 10000 # model_slices
N_batch_size = 100
[fsc]
pdb_path = "setup/skopi/examples/input/pdb/3iyf.pdb"
fsc_zoom = 0.6
fsc_nsearch = 420