# This toml file contains settings for the summit CI

[debug]
test = "CI settings for Summit"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "/gpfs/wolf/chm137/proj-shared/spinifel_data"
out_dir = "/gpfs/wolf/chm137/proj-shared/ci/${CI_PIPELINE_ID}/spinifel_output"
name = "2CEX-10k-2.h5"

[psana]
enable = false
ps_smd_n_events = 0

[runtime]
n_images_per_rank = 10
small_problem = true
use_cuda = true
use_cufinufft = true
use_single_prec = false

[gpu]
devices_per_node = 1
