# This toml file contains settings for the summit CI

[debug]
test = "Legion settings for Summit"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "/gpfs/alpine/scratch/iris/chm137/SPI_patterns"
out_dir = "/gpfs/alpine/scratch/iris/chm137/spinifel_data/spinifel_output"
name = "SPI_3iyf_dp005_128x128_149mesh_50000slices.h5"

[psana]
enable = false
ps_smd_n_events = 0

[runtime]
n_images_per_rank = 1000
small_problem = false
using_cuda = true
use_cufinufft = true
use_single_prec = false
chk_convergence = false

[gpu]
devices_per_node = 6
