# This toml file contains settings for the summit CI

[debug]
test = "CI settings for Summit"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "${test_data_dir}/2CEX"
out_dir = "${OUT_DIR}"
name = "2cexa_sim_clean_1k.h5"


[detector]
shape = [4, 512, 512]

[psana]
enable = false
ps_smd_n_events = 0

[runtime]
N_images_per_rank = 1000
use_cuda = true
use_cufinufft = true
use_cupy = true
use_single_prec = false
chk_convergence = true

[gpu]
devices_per_node = 1

[algorithm]
N_generations = 20
nER = 50
nHIO = 25
beta = 0.3
cutoff = 0.05
N_phase_loops = 10
N_clipping = 0
N_binning = 4
N_orientations = 10000
N_batch_size = 1000

[fsc]
pdb_path="setup/skopi/examples/input/pdb/2cex.pdb"
fsc_zoom=0.6
fsc_nsearch=420
fsc_min_cc=0.37         # see https://gitlab.osti.gov/mtip/spinifel/-/wikis/Perlmutter-Baseline-Convergence
fsc_min_change_cc=0.001
