# This toml file contains settings for the summit CI

[debug]
test = "CI settings for Summit"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "/gpfs/wolf/chm137/proj-shared/spinifel_data"
out_dir = "/gpfs/wolf/chm137/proj-shared/ci/${CI_PIPELINE_ID}/spinifel_output"
name = "2CEX-10k-2.h5"

[psana]
enable = false
ps_smd_n_events = 0

[runtime]
N_images_per_rank = 10
use_cuda = true
use_cufinufft = true
use_cupy = true
use_single_prec = false

[gpu]
devices_per_node = 1

[algorithm]
nER = 10
nHIO = 5
beta = 0.9
cutoff = 5e-2
N_phase_loops = 5
N_clipping = 1
N_binning = 4
N_orientations = 1000
N_batch_size = 1000

