# This toml file contains settings for the summit quicktart

[debug]
test = "Quickstart settings for Summit"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "/gpfs/alpine/world-shared/chm137/iris"
out_dir = "/gpfs/alpine/proj-shared/chm137/${LOGNAME}/spinifel_output"
name = "3iyf_128x128pixels_500k.h5"

[detector]
shape = [1, 128, 128]

[psana]
enable = false
ps_smd_n_events = 10000
ps_eb_nodes = 1
ps_srv_nodes = 0

[runtime]
N_images_per_rank = 1000
use_cuda = true
use_cufinufft = true
use_cupy = true
use_single_prec = false
chk_convergence = false

[algorithm]
N_generations = 20
nER = 50
nHIO = 50
beta = 0.9
cutoff = 0.1
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 200000  # model_slices
N_batch_size = 100