# This toml file contains place holder values, used to test the settings parser

[debug]
test = "loaded from toml file"
verbose = true
verbosity = 0
use_callmonitor = false

[data]
in_dir = "spinifel_data"
out_dir = "spinifel_output"
name = "data_file"

[psana]
enable = false
ps_smd_n_events = 0

[runtime]
N_images_per_rank = 10
use_cuda = false
use_cufinufft = false
use_cupy = false

[gpu]
devices_per_node = 0

[algorithm]
nER = 51
nHIO = 25
beta = 0.9
cutoff = 5e-2
N_phase_loops = 10
N_clipping = 0
N_binning = 0
N_orientations = 3000  # model_slices
N_batch_size = 100
